server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

datasource:
  url: jdbc:mysql://testdb-spring-boot.ctw0ggags8nt.us-east-1.rds.amazonaws.com:3306/project2?useUnicode=true&characterEncoding=UTF-8
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: qwer1234_good

springdoc:
  packages-to-scan: com.github.shoppingmall.shopping_mall.web.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha

  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

logging:
  config: classpath:logback.spring-local.xml
  level:
    org:
      hibernate:
        SQL: DEBUG


jwtpassword:
  source:  ${TOKEN_CODE}

post:
  file_path: ./static/post_img/

host:
  host_path: http://34.192.1.4:8080